//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido()
        {
            this.detalle_pedido = new HashSet<detalle_pedido>();
        }
    
        public int id_pedido { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_estado_pedido { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido> detalle_pedido { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual estado_pedido estado_pedido { get; set; }
    }
}
